# 1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [1]:
import numpy as np

In [9]:
one_d=np.array(np.arange(1,10,2))
print(one_d)
print("Dimension:",one_d.ndim)
print("Shape:",np.shape(one_d))

[1 3 5 7 9]
Dimension: 1
Shape: (5,)


In [10]:
two_d=np.array([np.arange(1,10,2),np.arange(20,30,2)])
print(two_d)
print("Dimension:",two_d.ndim)
print("Shape:",np.shape(two_d))

[[ 1  3  5  7  9]
 [20 22 24 26 28]]
Dimension: 2
Shape: (2, 5)


In [13]:
three_d=np.arange(48).reshape(2,3,8)
print(three_d)
print("Dimension:",three_d.ndim)
print("Shape:",np.shape(three_d))

[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]]

 [[24 25 26 27 28 29 30 31]
  [32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47]]]
Dimension: 3
Shape: (2, 3, 8)


# 2 . Create:
- an array of zeros of shape (3,3)
- an array of ones of shape (2,5)
- an array filled with 7

In [27]:
zeros=np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
ones=np.ones((5,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [29]:
full=np.full((3,3),7)
print(full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


# 3 . Create an array of even numbers between 10 and 50 using arange.


In [30]:
array=np.arange(10,50,2)
print(array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


# 4 . Create a 4×4 matrix from 0–15. Then , extract:
- the first row
- the last column
- a 2×2 subarray from the center

In [43]:
array=np.arange(0,16).reshape(4,4)
print(array)
print(array[0,:])
print(array[:,-1])
print(array[1:3,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[ 3  7 11 15]
[[ 5  6]
 [ 9 10]]


# 5 . Add a 1D array [1,2,3] to each row of a 3×3 matrix.

In [45]:
array_1=np.arange(9).reshape(3,3)
array_2=np.arange(1,4)
print(array_1)
print(array_2)
print(array_1+array_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 2 3]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


# 6 . Given two arrays A and B, compute:
- (A + B) / 2
- A^2 + B^2


In [50]:
a=np.arange(0,10)
b=np.arange(10,20)
print((a+b)/2)
print(a**2+b**2)


[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
[100 122 148 178 212 250 292 338 388 442]
