# Topic
1) [zip()](#1-zip)
2) [np.array()](#2-array)
3) [np.arange()](#3-arange)
4) [array slicing](#4-slicing)
5) [time-comparison-list-vs-numpy-array](#5-time-comparison-list-vs-numpy-array)
6) [2d array](#6-2d-array)
7) [memory-comparison-numpy-vs-list](#7-memory-comparison-numpy-vs-list)
8) [vectorization and list comprehension time complexity difference](#8-vectorization)

In [1]:
import numpy as np

In [8]:
import time


[Topic](#topic)
# 1 zip

In [31]:
t1=time.time()
size=1_000_000
list1=list(range(size))
list2=list(range(size))
list3=[x+y for x,y in zip(list1,list2)]
print(time.time()-t1)
print(list3[1])

0.11004948616027832
2


[Topic](#topic)
# 2) array()

In [32]:
t1=time.time()
ar1=np.array(np.arange(0,size))
ar2=np.array(np.arange(0,size))
ar3=ar1+ar2
print(time.time()-t1)
print(ar1[0])
print(type(ar1))

0.009958505630493164
0
<class 'numpy.ndarray'>


[Topic](#topic)
# 3) arange()

In [52]:
ar1=np.arange(1,10)
print(ar1)
print(type(ar1))
print(np.arange(1,10,2))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[1 3 5 7 9]


[Topic](#topic)
# 4) slicing 

In [23]:
print(list3[0:10])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


[Topic](#topic)
# 5) time comparison list vs numpy array

In [36]:
size=1_000_000
t1=time.time()
list1=list(range(size))
list2=list(range(size))
list3=[x+y for x,y in zip(list1,list2)]
t2=time.time()
print(t2-t1)

t3=time.time()
array1=np.array(np.arange(size))
array2=np.array(np.arange(size))
array3=array1+array2
t4=time.time()
print(t4-t3)

0.14596867561340332
0.007377147674560547


[Topic](#topic)
# 7) Memory comparison numpy vs list

In [41]:
import sys
print((sys.getsizeof(list3)*len(list3))/1024, " megabyte")
print(array3.nbytes/1024," megabyte")

8250710937.5  megabyte
7812.5  megabyte


[Topic](#topic)
# 6) 2d array

In [38]:
array_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)

[[1 2 3 4]
 [5 6 7 8]]


[Topic](#topic)
# 8) vectorization

In [43]:
t1=time.time()
list4=[x*2 for x in list1]
t2=time.time()
print(time.time()-t1)
t2=time.time()
array4=array1*2 # vectorization
print(time.time()-t2)

0.06417346000671387
0.0013196468353271484


[Topic](#topic)
# 9) np.zeros()

In [44]:
arr0=np.zeros((3,3))
arr0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

[Topic](#topic)
# 10) np.eye()

In [45]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[Topic](#topic)
# 11) np.ones()

In [47]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[Topic](#topic)
# 12) np.full()

In [51]:
print(np.full((3,3),7))

[[7 7 7]
 [7 7 7]
 [7 7 7]]
