# Install numpy 

In [1]:
!pip install numpy

  Using cached numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Using cached numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)


import numpy as np alias


In [4]:
import numpy as np
arr1=np.array([1,2,3,4,5]) # create a 1d array
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 2d array here (1,5) mean 1r 5c
arr2.reshape(5,1) # her 5r 1c


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]]) # 2r 5c
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [ ]:
print(np.arange(0,10,2)) # here 1st param is initializer,2nd param is limit  ,3rd param is i++ 
print(np.arange(0,10,2).reshape(5,1)) # reshape the array in 5r 1c

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [ ]:
np.ones((3,1)) # array's all element will 1

array([[1.],
       [1.],
       [1.]])

In [ ]:
np.eye(3) # identitcal array: main diagonal element will be 1, others will be zero 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr=np.array([[1,2,3,4],[4,5,6,7]])
print("Array:\n",arr)
print("Array dimension:\n",arr.shape)
print("Array size (total element):\n",arr.size)
print("Data type:\n",arr.dtype)
print("Element size of array:\n",arr.itemsize) # it depends of system bit like as win32,win64

Array:
 [[1 2 3 4]
 [4 5 6 7]]
Array dimension:
 (2, 4)
Array size (total element):
 8
Data type:
 int64
Element size of array:
 8


# Vectorized operation using numpy

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# Elementwise 
print("Addition operation:\n",arr1+arr2)
print("Substraction operation:\n",arr1-arr2)
print("Multiplication operation:\n",arr1*arr2)
print("Division operation:\n",arr1/arr2)

Addition operation:
 [11 22 33 44 55]
Substraction operation:
 [ -9 -18 -27 -36 -45]
Multiplication operation:
 [ 10  40  90 160 250]
Divide operation:
 [0.1 0.1 0.1 0.1 0.1]


# Mathematical operation using universal function

In [35]:
arr=np.array([1,2,3,4,5])
print(np.sqrt(arr)) # square root
print(np.exp(arr)) # exponential
print(np.sin(arr)) # sine 
print(np.log(arr)) # log

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


# Array slicing and indexing operation

In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)
print(arr[0][1]) # 0r 1c element
print(arr[1][0],arr[1][1],arr[1][2])
print(arr[1:]) # full row 
print(arr[:,:1]) # full col
print(arr[:2,3:]) # 4 5 9 10


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
6 7 8
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1]
 [ 6]
 [11]]
[[ 4  5]
 [ 9 10]]
[]


- here print(arr[i:n,j:m]), i is initializer that means which row and n is the ending row where iteration finished.j is the initializer for column and m is the ending column where iteration finished.

In [ ]:
print(arr[1:2,:2]) # 6 7 9 10
print(arr[1:2,3:]) 

[[6 7]]
[[ 9 10]]


# Modify array element


In [75]:
arr[1:2,:3]=3
print(arr) # 1st r 0th to 2nd column element will replace with 0

[[ 1  2  3  4  5]
 [ 3  3  3  9 10]
 [11 12 13 14 15]]


# Statistical concept 

In [82]:
print('Mean: ',np.mean(arr)) # arithmatic mean
print('Standard deviation: ',np.std(arr)) # standard deviation
print('Median: ',np.median(arr)) # median
print('Variance: ',np.var(arr)) # variance
print('Normalized array:\n',(arr-np.mean(arr))/np.std(arr)) # normalized data/standard normal distribution

Mean:  7.2
Standard deviation:  4.763752022653292
Median:  5.0
Variance:  22.69333333333333
Normalized array:
 [[-1.30149512 -1.09157655 -0.88165798 -0.67173942 -0.46182085]
 [-0.88165798 -0.88165798 -0.88165798  0.37785342  0.58777199]
 [ 0.79769056  1.00760912  1.21752769  1.42744626  1.63736483]]


# Logical Operations

In [102]:
data=np.array([np.arange(0,1000,2)])
print('Data between 50 to 100: ',data[(data>50) & (data<100)])  # just use logical signs &,^
print('Data: ',data[(data%2==0) & ((data<100) & (data>90))])

Data between 50 to 100:  [52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
Data:  [92 94 96 98]
