In [2]:
# install numpy
!pip install numpy

In [6]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.reshape(1,5)) # 1 row 5 column

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3 4 5]]


In [10]:
import numpy as np
arr1=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr1)
print(arr1.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.ones((3,4)) # identity matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(3,4) # 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [23]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.size)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.itemsize)

[[1 2 3]
 [4 5 6]]
6
2
(2, 3)
int64
8


In [27]:
# Numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([40,50,60,70,80])

# addition
print("Addition: ", arr1+arr2)

# substraction
print(arr1-arr2)

# multiplication

print(arr1*arr2)

# division

print(arr1/arr2)

Addition:  [41 52 63 74 85]
[-39 -48 -57 -66 -75]
[ 40 100 180 280 400]
[0.025      0.04       0.05       0.05714286 0.0625    ]


In [30]:
# universal function means which effect all over array
arr1=np.array([10,20,30,40,50])

# sqrt
print(np.sqrt(arr1))

# sine
print(np.sin(arr1))

# exponential
print(np.exp(arr1))

# natural log
print(np.log(arr1))


[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
