In [1]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 186.4 kB/s  0:01:12 eta 0:00:010:00:03


In [2]:
import numpy as np
arr=np.array([1,2])
print(arr)

[1 2]


In [3]:
print(np.array([1,2,3]).ndim)

1


In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
arr=np.array([1,2,3])
print(arr.dtype)

int64


In [6]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.full((2,2), np.inf) 

array([[inf, inf],
       [inf, inf]])

In [8]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[:,1])

[20 50]


In [9]:
np.random.rand(2,3)

array([[0.94849352, 0.57388431, 0.80723369],
       [0.08519343, 0.8628661 , 0.93349809]])

In [11]:
arr=np.array([1,2,3,4,5])
arr[1:4]=0
print(arr)

[1 0 0 0 5]


In [14]:
print(np.ravel(np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]),order="C"))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 