In [2]:
!pip install numpy

In [3]:
import numpy as np
arr=np.array([1,2])
print(arr)

[1 2]


In [4]:
print(np.array([1,2,3]).ndim)

1


In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
arr=np.array([1,2,3])
print(arr.dtype)

int64


In [7]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
np.full((2,2), np.inf) 

array([[inf, inf],
       [inf, inf]])

In [9]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[:,1])

[20 50]


In [10]:
np.random.rand(2,3)

array([[0.97314758, 0.67628345, 0.40436551],
       [0.25063499, 0.41894081, 0.6169063 ]])

In [11]:
arr=np.array([1,2,3,4,5])
arr[1:4]=0
print(arr)

[1 0 0 0 5]


In [14]:
print(np.ravel(np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]),order="C"))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
