In [1]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 186.4 kB/s  0:01:12 eta 0:00:010:00:03


In [1]:
import numpy as np
arr=np.array([1,2])
print(arr)

[1 2]


In [3]:
print(np.array([1,2,3]).ndim)

1


In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
arr=np.array([1,2,3])
print(arr.dtype)

int64


In [6]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.full((2,2), np.inf) 

array([[inf, inf],
       [inf, inf]])

In [8]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[:,1])

[20 50]


In [9]:
np.random.rand(2,3)

array([[0.94849352, 0.57388431, 0.80723369],
       [0.08519343, 0.8628661 , 0.93349809]])

In [11]:
arr=np.array([1,2,3,4,5])
arr[1:4]=0
print(arr)

[1 0 0 0 5]


In [14]:
print(np.ravel(np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]),order="C"))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 

In [2]:
import pandas as pd

In [3]:
np.random.seed(42)
ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])
DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})
DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


# Q1. Create NumPy arrays from the ages and salaries data generated above. Print both arrays and display their dtype, ndim, shape, and size.

In [12]:
ages_numpy_array=np.array(ages)
salaries_numpy_array=np.array(salaries)
print(f"Array:{ages_numpy_array}, dtype: {ages_numpy_array.dtype}, ndim: {ages_numpy_array.ndim}, shape: {ages_numpy_array.shape}, size: {ages_numpy_array.size}")
print(f"Array:{salaries_numpy_array}, dtype: {salaries_numpy_array.dtype}, ndim: {salaries_numpy_array.ndim}, shape: {salaries_numpy_array.shape}, size: {salaries_numpy_array.size}")

Array:[56 46 32 25 38 56 36 40 28 28], dtype: int64, ndim: 1, shape: (10,), size: 10
Array:[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311], dtype: int64, ndim: 1, shape: (10,), size: 10


# Q2. Using the salaries array, find and print the highest and lowest salary values. Also, calculate and print the average salary and age using NumPy functions.

In [19]:
print(f"Highest salary: {np.max(salaries_numpy_array)},\nlowest salary: {np.min(salaries_numpy_array)},\naverage salary: {np.average(salaries_numpy_array)},\naverage age: {np.average(ages_numpy_array)}")


Highest salary: 89735,
lowest salary: 30769,
average salary: 57446.9,
average age: 38.5


# Q3. From the ages array, filter and print all ages greater than 30 using a boolean condition. Then count and print how many employees are older than 30.

In [28]:
print(f"{ages_numpy_array[ages_numpy_array>30]},{np.sum(ages_numpy_array>30)}")

[56 46 32 38 56 36 40],7
