In [2]:
!pip install numpy

In [3]:
import numpy as np
arr=np.array([1,2])
print(arr)

[1 2]


In [3]:
print(np.array([1,2,3]).ndim)

1


In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
arr=np.array([1,2,3])
print(arr.dtype)

int64


In [6]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.full((2,2), np.inf) 

array([[inf, inf],
       [inf, inf]])

In [8]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[:,1])

[20 50]


In [9]:
np.random.rand(2,3)

array([[0.94849352, 0.57388431, 0.80723369],
       [0.08519343, 0.8628661 , 0.93349809]])

In [11]:
arr=np.array([1,2,3,4,5])
arr[1:4]=0
print(arr)

[1 0 0 0 5]


In [14]:
print(np.ravel(np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]),order="C"))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 

In [1]:
import pandas as pd

In [4]:
np.random.seed(42)
ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])
DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})
DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


# Q1. Create NumPy arrays from the ages and salaries data generated above. Print both arrays and display their dtype, ndim, shape, and size.

In [5]:
ages_numpy_array=np.array(ages)
salaries_numpy_array=np.array(salaries)
print(f"Array:{ages_numpy_array}, dtype: {ages_numpy_array.dtype}, ndim: {ages_numpy_array.ndim}, shape: {ages_numpy_array.shape}, size: {ages_numpy_array.size}")
print(f"Array:{salaries_numpy_array}, dtype: {salaries_numpy_array.dtype}, ndim: {salaries_numpy_array.ndim}, shape: {salaries_numpy_array.shape}, size: {salaries_numpy_array.size}")

Array:[56 46 32 25 38 56 36 40 28 28], dtype: int64, ndim: 1, shape: (10,), size: 10
Array:[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311], dtype: int64, ndim: 1, shape: (10,), size: 10


# Q2. Using the salaries array, find and print the highest and lowest salary values. Also, calculate and print the average salary and age using NumPy functions.

In [6]:
print(f"Highest salary: {np.max(salaries_numpy_array)},\nlowest salary: {np.min(salaries_numpy_array)},\naverage salary: {np.average(salaries_numpy_array)},\naverage age: {np.average(ages_numpy_array)}")


Highest salary: 89735,
lowest salary: 30769,
average salary: 57446.9,
average age: 38.5


# Q3. From the ages array, filter and print all ages greater than 30 using a boolean condition. Then count and print how many employees are older than 30.

In [7]:
print(f"{ages_numpy_array[ages_numpy_array>30]},{np.sum(ages_numpy_array>30)}")

[56 46 32 38 56 36 40],7


# Q4. Create a new NumPy array that increases every employee’s age by 5 years (without modifying the original array). Print the new updated ages array.

In [8]:
copy_ages_numpy_array=ages.copy()
copy_ages_numpy_array+=5
print(copy_ages_numpy_array)

[61 51 37 30 43 61 41 45 33 33]


# Q5. Using NumPy, calculate the total salary expense (sum of all salaries) and the difference between the maximum and minimum salary. Print both results.


In [12]:
total_salary_expense=salaries_numpy_array.sum()
maximum_salary=salaries_numpy_array.max()
minimum_salary=salaries_numpy_array.min()
print(f"Total salary expense: {total_salary_expense},\ndifference between the maximum and minimum salary: {maximum_salary-minimum_salary}")

Total salary expense: 574469,
difference between the maximum and minimum salary: 58966


# Q6. Load the employees.csv file into a Pandas DataFrame. Display the first 5 rows, and check basic info using info() and summary statistics using describe().


In [16]:
df=pd.read_csv("employees.csv")
print(df.head(5))
print(df.info())
print(df.describe())

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes
None
             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000


# Q7. Display only the id, age, and salary columns. Then show the last 3 rows using tail().

In [23]:
print(df.loc[:,['id','age','salary']])
print(df.tail(3))

   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311
   id  age  salary   dept
7   8   40   86101     IT
8   9   28   32433  Sales
9  10   28   35311     HR


# Q8. Filter the DataFrame to show only employees who work in the IT department. Print the result and show the total number of IT employees.


In [29]:
it=df.loc[df['dept']=="IT"]
print(it)
print(it.count())

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
id        3
age       3
salary    3
dept      3
dtype: int64


# Q9. Sort the DataFrame by salary in descending order and display the top 3 highest-paid employees along with their department and age.


In [40]:
sorted_df=df.sort_values(by='salary',ascending=0)
print(sorted_df.head(3))

   id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR


# Q10. Replace all salary values greater than 80000 with 80000 using loc. Then calculate and print the new average salary of all employees after replacement.



In [45]:
copy_df=df
copy_df.loc[copy_df['salary']>80000,'salary']=80000
print(np.average(np.array(df['salary'])))

55863.3
