# Topic
1) [zip()](#1-zip)
2) [np.array()](#2-array)
3) [np.arange()](#3-arange)
4) [array slicing](#4-slicing)
5) [time-comparison-list-vs-numpy-array](#5-time-comparison-list-vs-numpy-array)
6) [2d array](#6-2d-array)
7) [memory-comparison-numpy-vs-list](#7-memory-comparison-numpy-vs-list)
8) [vectorization and list comprehension time complexity difference](#8-vectorization)
10) [np.zeros()](#9-npzeros)
11) [np.eye()](#10-npeye)
12) [np.ones()](#11-npones)
13) [np.full()](#12-npfull)
14) [np.linspace()](#13-nplinspace)
15) [arraay.ndim()](#14-arrayndim)
16) [array.size()](#15-arraysize)
17) [print-data-type-float-explicitly](#17-print-data-type-float-explicitly)
18) [array.astype()](#18-arrayastype)
19) [array.reshape()](#19-arrayreshape)
20) [array.flatten()](#20-arrayflatten)
21) [indexing & slicing-in-numpy](#21-indexing--slicing-for-numpy)
22) [view vs copy in numpy](#22-view-vs-copy-in-numpy)
23) [fancy-indexing](#23-fancy-indexing)
24) [boolean-masking](#24-boolean-masking)
25) [np.sum(array,axis=0) && np.sum(array,axis=0)](#25-npsumarrayaxis0--npsumarrayaxis0)
26) [comma-separated-indexing](#26-comma-separated-indexing)
27) [2d-dimensional-array-index-and-slicing](#27-2d-dimensional-array-index-and-slicing)
28) [3d-dimensional-array-index-and-slicing](#28-3d-dimensional-array-index-and-slicing)
29) [changing-data-along-an-axis](#29-changing-data-along-an-axis)
30) [data-types-in-numpy](#30-data-types-in-numpy)
31) [broadcasting](#31-broadcasting)
32) [mean-std-normalized_data](#32-mean-std-normalized_data)
33) [np.min(array)](#33-npminarray)
34) [np.max(array)](#34-npmaxarray)
35) [np.sum(array)](#35-npsumarray)
36) [np.prod(array)](#36-npprodarray)
37) [np.median(array)](#37-npmedianarray)
38) [np.log(array)](#38-nplogarray)
39) [np.percentile(array,n-th-percentile)](#39-nppercentilearrayn-th-percentile)
40) [np.argmin(array)](#40-npargminarray)
41) [np.argmax(array)](#41-npargmaxarray)
42) [np.unique(array0](#42-npuniquearray)
43) [np.corrcoef(array) --> for-correlation-coefficient](#43-npcorrcoefarray--for-correlation-coefficient)
44) [np.cumsum(array) -->for-cumulative-sum](#44-npcumsumarray--for-cumulative-sum)
45) [np.diff(array) -->for-differences-between-nth-element](#45-npdiffarray--for-differences-between-nth-element)
46) [np.linspace(array) with explanation](#46-nplinspacearray)
47) [np.log(array)](#47-nplogarray)
48) [np.exp(array)](#48-npexparray)

# Optional
- [SMID, RISC-V, MISC-V](#-simd-single-instruction-multiple-dataset-instruction-sets)

In [ ]:
!pip install numpy

In [3]:
import numpy as np

In [ ]:
import time


[Topic](#topic)
# 1 zip

In [ ]:
t1=time.time()
size=1_000_000
list1=list(range(size))
list2=list(range(size))
list3=[x+y for x,y in zip(list1,list2)]
print(time.time()-t1)
print(list3[1])

0.07363724708557129
2


[Topic](#topic)
# 2) array()

In [ ]:
t1=time.time()
ar1=np.array(np.arange(0,size))
ar2=np.array(np.arange(0,size))
ar3=ar1+ar2
print(time.time()-t1)
print(ar1[0])
print(type(ar1))

0.00714421272277832
0
<class 'numpy.ndarray'>


[Topic](#topic)
# 3) arange()

In [ ]:
ar1=np.arange(1,10)
print(ar1)
print(type(ar1))
print(np.arange(1,10,2))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[1 3 5 7 9]


[Topic](#topic)
# 4) slicing 

In [ ]:
print(list3[0:10])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


[Topic](#topic)
# 5) time comparison list vs numpy array

In [ ]:
size=1_000_000
t1=time.time()
list1=list(range(size))
list2=list(range(size))
list3=[x+y for x,y in zip(list1,list2)]
t2=time.time()
print(t2-t1)

t3=time.time()
array1=np.array(np.arange(size))
array2=np.array(np.arange(size))
array3=array1+array2
t4=time.time()
print(t4-t3)

0.0871269702911377
0.00564122200012207


[Topic](#topic)
# 7) Memory comparison numpy vs list

In [ ]:
import sys
print((sys.getsizeof(list3)*len(list3))/1024, " megabyte")
print(array3.nbytes/1024," megabyte")

8250710937.5  megabyte
7812.5  megabyte


[Topic](#topic)
# 6) 2d array

In [ ]:
array_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)

[[1 2 3 4]
 [5 6 7 8]]


[Topic](#topic)
# 8) vectorization

In [ ]:
t1=time.time()
list4=[x*2 for x in list1]
t2=time.time()
print(time.time()-t1)
t2=time.time()
array4=array1*2 # vectorization
print(time.time()-t2)

0.026114702224731445
0.0017902851104736328


[Topic](#topic)
# 9) np.zeros()

In [ ]:
arr0=np.zeros((3,3))
arr0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

[Topic](#topic)
# 10) np.eye()

In [ ]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[Topic](#topic)
# 11) np.ones()

In [ ]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[Topic](#topic)
# 12) np.full()

In [ ]:
print(np.full((3,3),7))

[[7 7 7]
 [7 7 7]
 [7 7 7]]


[Topic](#topic)
# 13) np.linspace()

In [ ]:
print(np.linspace(1,100,5))

[  1.    25.75  50.5   75.25 100.  ]


[Topic](#topic)
# 14) array.ndim

In [ ]:
ar1=np.array([[1,2,3,4],[4,5,6,7]])
print(ar1.ndim)

2


[Topic](#topic)
# 15) array.size

In [ ]:
print(ar1.size)

8


[Topic](#topic)
# 16) array.dtype

In [ ]:
print(ar1.dtype)

int64


[Topic](#topic)
# 17) print data type float explicitly

In [ ]:
print(np.array([1,2,3,4],dtype="float32"))

[1. 2. 3. 4.]


[Topic](#topic)
# 18) array.astype()

In [ ]:
print(ar1.astype("float"))

[[1. 2. 3. 4.]
 [4. 5. 6. 7.]]


[Topic](#topic)
# 19) array.reshape()

In [ ]:
print(ar1.reshape(2,4))
print(ar1.reshape(4,2))

[[1 2 3 4]
 [4 5 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


[Topic](#topic)
# 20) array.flatten()

In [ ]:
print(np.array([[1,2,3,4],[5,6,7,8]]).flatten())

[1 2 3 4 5 6 7 8]


In [5]:
print(np.ravel(np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]]),order="F"))

[ 1  4  8  2  5  9  3  6 10  4  7 11]


[Topic](#topic)
# 21) indexing & slicing for numpy

In [ ]:

flat=ar1.flatten()
print(flat)


[1 2 3 4 4 5 6 7]


In [ ]:
flat[0:]

array([1, 2, 3, 4, 4, 5, 6, 7])

In [ ]:
flat[0:2]

array([1, 2])

In [ ]:
flat[:3]

array([1, 2, 3])

In [ ]:
flat[0:5:1]

array([1, 2, 3, 4, 4])

[Topic](#topic)
# 22) view vs copy in numpy

In [ ]:
flat=ar1.flatten()
flat


array([1, 2, 3, 4, 4, 5, 6, 7])

In [ ]:
b=flat[0:3]
b

array([1, 2, 3])

In [ ]:
b[0]=1000

In [ ]:
flat # slicing returns the view of a array not copy because in numpy slicing uses same memory address. for solving this issue use b=flat[0:3].copy() 

array([1000,    2,    3,    4,    4,    5,    6,    7])

In [ ]:
b=flat[0:3].copy() # for solve
b[0]=0
flat

array([1000,    2,    3,    4,    4,    5,    6,    7])

In [ ]:
b

array([0, 2, 3])

[Topic](#topic)
# 23) fancy indexing

In [ ]:
print(flat[[1,2,3]]) # arrray[index1,index2,index3]

[2 3 4]


[Topic](#topic)
# 24) boolean masking

In [ ]:
print(flat[flat>100]) # array[array>condition]

[1000]


[Topic](#topic)
# 25) np.sum(array,axis=0) && np.sum(array,axis=0)

In [ ]:
arr=np.array([np.arange(10),np.arange(10)])
print(arr)
print("Sum of rows: ",np.sum(arr,axis=1))
print("Sum of columns: ",np.sum(arr,axis=0))

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
Sum of rows:  [45 45]
Sum of columns:  [ 0  2  4  6  8 10 12 14 16 18]


[Topic](#topic)
# 26) comma separated indexing

In [ ]:
print(arr[0,0])
print(arr[0:2,1])
print(arr[1,5:7]) 
# find 

0
[1 1]
[5 6]


[Topic](#topic)
# 27) 2d Dimensional Array Index And Slicing

In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
# sum of every rows
print(np.sum(arr,axis=1))
# sum of every column
print(np.sum(arr,axis=0))

[15 40 65]
[18 21 24 27 30]


In [ ]:
arr[0,1] # index

np.int64(2)

In [ ]:
# print [4,5],[9,10]
arr[0:2,3:5]

array([[ 4,  5],
       [ 9, 10]])

[Topic](#topic)
# 28) 3d Dimensional Array Index And Slicing

In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3d array= array[depth][row][column] . depth means the index number of 2d arrays.
arr.shape

(2, 2, 3)

In [ ]:
# print [1,2,3],[4,5,6]
arr[0,0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# print [2,3],[5,6]

arr[0,0:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
# print [1,7]
arr[:,0,0:1]

array([[1],
       [7]])

[Topic](#topic)
# 29) Changing Data Along an Axis

In [ ]:
arr[0,0,0]=0

In [ ]:
arr[0,0,0]

np.int64(0)

[Topic](#topic)
# 30) Data Types In Numpy

### Common Data Types in NumPy:
- int32, int64: Integer types with different bit sizes.
- float32, float64: Floating-point types with different precision.
- bool: Boolean data type.
- complex64, complex128: Complex number types.
- object: For storing objects (e.g., Python objects, strings).


In [ ]:
arr=np.array(np.arange(0,10))

In [ ]:
arr.astype("float32")

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr=np.array(np.arange(0,10),dtype="float32")

In [ ]:
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [ ]:
arr.astype("float64")

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
arr1=np.array(np.arange(0,10),dtype="int64")
arr2=np.array(np.arange(0,10),dtype="int32")
arr3=np.array(np.arange(0,10),dtype="float32")
arr4=np.array(np.arange(0,10),dtype="float64")


In [ ]:
arr1.nbytes


80

In [ ]:
arr2.nbytes


40

In [ ]:
arr3.nbytes


40

In [ ]:
arr4.nbytes

80

In [ ]:
arr5=np.array(["apple","banana","fish","eagle"])
arr6=np.array(["apple","banana","fish","eagle"],dtype="U10")

In [ ]:
arr5.nbytes

96

In [ ]:
arr6.nbytes

160

In [ ]:
arr7=np.array([1+2j,1-2j,1+3j],dtype="complex64")
arr8=np.array([1+2j,1-2j,1+3j],dtype="complex128")

In [ ]:
arr7.nbytes

24

In [ ]:
arr8.nbytes

48

In [ ]:
arr9=np.array([{"Hello":"1"},"Banana",13],dtype="object")

In [ ]:
arr9.nbytes

24

[Topic](#topic)
# 31) Broadcasting

### Broadcasting use no extra memory. Works based on SIMD CPU Optimization.
##### 🔧 SIMD (Single Instruction Multiple Dataset) Instruction Sets
| Vendor | Instruction Set   | Vector Width |
| ------ | ----------------- | ------------ |
| Intel CISC (Complex Instruction Set Computer)  | SSE (128-bit)     | 4 floats     |
| Intel CISC (Complex Instruction Set Computer) | AVX (256-bit)     | 8 floats     |
| Intel CISC (Complex Instruction Set Computer) | AVX-512 (512-bit) | 16 floats    |
| ARM   CISC (Complex Instruction Set Computer) | NEON (128-bit)    | 4 floats     |
| RISC-V (Reduced Instruction Set Computer) | V extension       | Flexible     |


In [ ]:
arr10=np.array(np.arange(0,10))
arr11=np.array(np.arange(0,10))
arr12=arr10+arr11
arr12

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr12**2

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324])

In [ ]:
arr13=np.array([1,2,3,4,5])
arr14=np.array([[6,7,8,9,10],[11,12,13,14,15]])
arr15=arr13+arr14
print(arr15)

[[ 7  9 11 13 15]
 [12 14 16 18 20]]


[Topic](#topic)
# 32) mean, std, normalized_data 

In [ ]:
arr1=np.array([1,2,3,4,5])
mean=arr1.mean()
standard_deviation=arr1.std()
normalized_data=(arr1-mean)/standard_deviation
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
# normalized_data based on each column
arr2=np.array([[10,20,30],[40,50,60],[70,80,90]])
mean=arr2.mean(axis=0)
std=arr2.std(axis=0)
normalized_data=(arr2-mean)/std
print(normalized_data)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


[Topic](#topic)
# 33) np.min(array)

In [ ]:
ar1=np.array(np.arange(10,20,3))

In [ ]:
np.min(ar1)

np.int64(10)

[Topic](#topic)
# 34) np.max(array)

In [ ]:
np.max(ar1)

np.int64(19)

[Topic](#topic)
# 34) np.var(array)

In [ ]:
np.var(ar1)

np.float64(11.25)

[Topic](#topic)
# 35) np.sum(array)

In [ ]:
np.sum(ar1)

np.int64(58)

[Topic](#topic)
# 36) np.prod(array)

In [ ]:
np.prod(ar1)

np.int64(39520)

[Topic](#topic)
# 37) np.median(array)

In [ ]:
np.median(ar1)

np.float64(14.5)

[Topic](#topic)
# 38) np.log(array)

In [ ]:
np.log(ar1)

array([2.30258509, 2.56494936, 2.77258872, 2.94443898])

[Topic](#topic)
# 39) np.percentile(array,n th percentile)

In [ ]:
np.percentile(ar1,10)

np.float64(10.9)

[Topic](#topic)
# 40) np.argmin(array)

In [ ]:
np.argmin(ar1) # return minimum element index


np.int64(0)

[Topic](#topic)
# 41) np.argmax(array)

In [ ]:
np.argmax(np.array([10,90,10]))

np.int64(1)

[Topic](#topic)
# 42) np.unique(array)

In [ ]:
np.unique(ar1)

array([10, 13, 16, 19])

[Topic](#topic)
# 43) np.corrcoef(array)  for correlation coefficient

In [ ]:
np.corrcoef(ar1)

np.float64(1.0)

[Topic](#topic)
# 44) np.cumsum(array)  for cumulative sum

In [ ]:
np.cumsum(ar1)

array([10, 23, 39, 58])

[Topic](#topic)
# 45) np.diff(array)  for differences between nth element

In [ ]:
np.diff(ar1)

array([3, 3, 3])

[Topic](#topic)
# 46) np.linspace(array) 

np.linspace() হল NumPy লাইব্রেরির একটি ফাংশন, যার কাজ হল দুটি সংখ্যার মধ্যে নির্দিষ্ট সংখ্যক সমান ব্যবধানের মান তৈরি করা।

In [ ]:
np.linspace(0,10,1)

array([0.])

In [ ]:
np.linspace(1,16,4)

array([ 1.,  6., 11., 16.])

[Topic](#topic)
# 47) np.log(array) 

In [ ]:
np.log(ar1)

array([2.30258509, 2.56494936, 2.77258872, 2.94443898])

[Topic](#topic)
# 48) np.exp(array) 

In [ ]:
np.exp(ar1)

array([2.20264658e+04, 4.42413392e+05, 8.88611052e+06, 1.78482301e+08])

In [6]:
np.rad2deg(45)

np.float64(2578.3100780887044)

In [ ]:
np.deg2rad(90)

In [38]:
x=np.arange(1,11)

# 48) Concatenate

In [39]:
y=np.arange(5,15)
print(np.concatenate((x,y),axis=0))

[ 1  2  3  4  5  6  7  8  9 10  5  6  7  8  9 10 11 12 13 14]


# 49) Logical operation

In [40]:
equal= x==y
print(equal)

[False False False False False False False False False False]


In [41]:
greater_than= x>y
print(greater_than)

[False False False False False False False False False False]


In [42]:
print(np.all(greater_than)) # when all is true

False


In [43]:
print(np.any(greater_than)) # when any is true return true

False


In [44]:
print(np.any(y>x))

True


# 50) Sorting

In [45]:
x=np.array([1,5,10,4,3,2,0])

In [46]:
print(np.sort(x))

[ 0  1  2  3  4  5 10]


In [47]:
x=np.array([[5,4,3,2,1],[10,9,8,7,6]])
print(np.sort(x,axis=1)) # axis=1 for rowwsie sorting 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [49]:
print(np.sort(x,axis=0)) # axis=0 for columnwise sorting

[[ 5  4  3  2  1]
 [10  9  8  7  6]]


# 51) Searching & Counting

In [54]:
print(np.where(x==1)) # return index only

(array([0]), array([4]))


In [55]:
print(np.where(x>8,x,x)) # return array only

[[ 5  4  3  2  1]
 [10  9  8  7  6]]


# 52) Counting

In [62]:
arr=np.random.randint(1,100,size=(1000))


In [66]:
print(np.count_nonzero(arr>10))

896


In [67]:
a=arr[arr<2]

In [69]:
print(a)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [79]:
unique_value,count=np.unique(arr,return_counts=True)
x=[x+y for x,y in zip(unique_value,count)]
print(unique_value)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


# 52) Determinant of matrix

In [95]:
arr=np.array([np.arange(1,3),np.arange(1,3)])

In [98]:
print(arr)

[[1 2]
 [1 2]]


In [96]:
det=np.linalg.det(arr)

In [97]:
print(det)

0.0


# 53) Trace

In [99]:
print(np.trace(arr))

3


# 54) Dot product

In [100]:
print(np.dot(arr,arr))

[[3 6]
 [3 6]]


In [103]:
print(arr.shape[0])

2


# Probeml-1:
https://www.deep-ml.com/problems/1

In [104]:
import numpy as np
def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	
    a=np.array(a)
    b=np.array(b)
    shape_a=a.shape
    shape_b=b.shape
    if shape_a[1]!=shape_b[0]:
        return -1
    else:
        dot=np.dot(a,b)
        return dot


# Problem-2:
https://www.deep-ml.com/problems/4

In [ ]:
import numpy as np
def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
	mat=np.array(matrix)
	if mode=="column":
		means=mat.mean(axis=0)
	else:
		means=mat.mean(axis=1)
	return means

# 55) Transpose matrix

In [114]:
print(np.transpose([[1,2,3],[4,5,6]]))

[[1 4]
 [2 5]
 [3 6]]


# Problem-3:
https://www.deep-ml.com/problems/2

In [ ]:
import numpy as np
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
    a=np.array(a)
    b=np.transpose(a)
	return b