In [1]:
import numpy as np

In [2]:
a=np.array([2,1,3])
b=np.array([1,3,3])
print(a)
print(b)

[2 1 3]
[1 3 3]


In [3]:
add_ab=a+b
sub_ab=a-b
print(add_ab)
print(sub_ab)

[3 4 6]
[ 1 -2  0]


### dot product

In [9]:
dot_product=np.dot(a,b)
dot_pro=a@b #shortcut
print(dot_pro)
print(dot_product)

14
14


### norms


In [12]:
l1_norm=np.linalg.norm(a,ord=1) # l1 norm length or magnitude  
print(l1_norm)
# l2 norm, the usual length
l2_a=np.linalg.norm(a)
print(l2_a)

6.0
3.7416573867739413


In [15]:
# normalizing unit vector
unit_a=a/np.linalg.norm(a)
l2_unia_a=np.linalg.norm(unit_a)
print(unit_a)
print(l2_unia_a)

[0.53452248 0.26726124 0.80178373]
1.0
